### ISSUE TITLE
Error compile

### ISSUE THREAD

**Issue by monyonk** [atorrescogollo/offensive-tor-toolkit#4]
I got error while compiling the the code 

+ for file in *.go
+ go build -ldflags=-extldflags=-static -o build/ reverse-shell-over-tor.go
# command-line-arguments
/usr/bin/ld: /tmp/go-link-789265993/000945.o: in function `check_private_dir':
/go/pkg/mod/github.com/ipsn/go-libtor@v1.0.380/libtor/../tor/src/../src/lib/fs/dir.c:216: warning: Using 'getgrgid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-789265993/000952.o: in function `tor_getpwnam':
/go/pkg/mod/github.com/ipsn/go-libtor@v1.0.380/libtor/../tor/src/../src/lib/fs/userdb.c:80: warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-789265993/000952.o: in function `tor_getpwuid':
/go/pkg/mod/github.com/ipsn/go-libtor@v1.0.380/libtor/../tor/src/../src/lib/fs/userdb.c:110: warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-789265993/000004.o: in function `_cgo_26061493d47f_C2func_getaddrinfo':
/tmp/go-build/cgo-gcc-prolog:58: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-789265993/000120.o: in function `BIO_gethostbyname':
/go/pkg/mod/github.com/ipsn/go-libtor@v1.0.380/libtor/../openssl/include/../crypto/bio/b_sock.c:113: warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-789265993/000019.o: in function `evutil_unparse_protoname':
/go/pkg/mod/github.com/ipsn/go-libtor@v1.0.380/libtor/../libevent/compat/../evutil.c:1133: warning: Using 'getprotobynumber' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-789265993/000019.o: in function `evutil_parse_servname':
/go/pkg/mod/github.com/ipsn/go-libtor@v1.0.380/libtor/../libevent/compat/../evutil.c:1105: warning: Using 'getservbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

**Comment by atorrescogollo** [comment]
They are just glibc warnings when compiling it statically. They are not actual errors.

NOTE: I'm currently working on a brand-new implementation. Subscribe to notifications [here](https://github.com/atorrescogollo/offensive-tor-toolkit/issues/3) if you want to be notified when it's ready
